python3 arithmetic/matrix/ntm_matrix_adder.py
python3 arithmetic/matrix/ntm_matrix_divider.py
python3 arithmetic/matrix/ntm_matrix_multiplier.py
python3 arithmetic/scalar/ntm_scalar_adder.py
python3 arithmetic/scalar/ntm_scalar_divider.py
python3 arithmetic/scalar/ntm_scalar_multiplier.py
python3 arithmetic/tensor/ntm_tensor_adder.py
python3 arithmetic/tensor/ntm_tensor_divider.py
python3 arithmetic/tensor/ntm_tensor_multiplier.py
python3 arithmetic/vector/ntm_vector_adder.py
python3 arithmetic/vector/ntm_vector_divider.py
python3 arithmetic/vector/ntm_vector_multiplier.py
python3 controller/FNN/convolutional/ntm_controller.py
python3 controller/FNN/standard/ntm_controller.py
python3 controller/LSTM/convolutional/ntm_activation_gate_vector.py
python3 controller/LSTM/convolutional/ntm_controller.py
python3 controller/LSTM/convolutional/ntm_forget_gate_vector.py
python3 controller/LSTM/convolutional/ntm_hidden_gate_vector.py
python3 controller/LSTM/convolutional/ntm_input_gate_vector.py
python3 controller/LSTM/convolutional/ntm_output_gate_vector.py
python3 controller/LSTM/convolutional/ntm_state_gate_vector.py
python3 controller/LSTM/standard/ntm_activation_gate_vector.py
python3 controller/LSTM/standard/ntm_controller.py
python3 controller/LSTM/standard/ntm_forget_gate_vector.py
python3 controller/LSTM/standard/ntm_hidden_gate_vector.py
python3 controller/LSTM/standard/ntm_input_gate_vector.py
python3 controller/LSTM/standard/ntm_output_gate_vector.py
python3 controller/LSTM/standard/ntm_state_gate_vector.py
python3 controller/transformer/components/ntm_masked_multi_head_attention.py
python3 controller/transformer/components/ntm_masked_scaled_dot_product_attention.py
python3 controller/transformer/components/ntm_multi_head_attention.py
python3 controller/transformer/components/ntm_scaled_dot_product_attention.py
python3 controller/transformer/fnn/ntm_fnn.py
python3 controller/transformer/functions/ntm_layer_norm.py
python3 controller/transformer/functions/ntm_positional_encoding.py
python3 controller/transformer/inputs/ntm_inputs_vector.py
python3 controller/transformer/inputs/ntm_keys_vector.py
python3 controller/transformer/inputs/ntm_queries_vector.py
python3 controller/transformer/inputs/ntm_values_vector.py
python3 controller/transformer/lstm/ntm_activation_gate_vector.py
python3 controller/transformer/lstm/ntm_forget_gate_vector.py
python3 controller/transformer/lstm/ntm_hidden_gate_vector.py
python3 controller/transformer/lstm/ntm_input_gate_vector.py
python3 controller/transformer/lstm/ntm_lstm.py
python3 controller/transformer/lstm/ntm_output_gate_vector.py
python3 controller/transformer/lstm/ntm_state_gate_vector.py
python3 controller/transformer/top/ntm_controller.py
python3 controller/transformer/top/ntm_decoder.py
python3 controller/transformer/top/ntm_encoder.py
python3 dnc/memory/dnc_addressing.py
python3 dnc/memory/dnc_allocation_weighting.py
python3 dnc/memory/dnc_backward_weighting.py
python3 dnc/memory/dnc_forward_weighting.py
python3 dnc/memory/dnc_matrix_content_based_addressing.py
python3 dnc/memory/dnc_memory_matrix.py
python3 dnc/memory/dnc_memory_retention_vector.py
python3 dnc/memory/dnc_precedence_weighting.py
python3 dnc/memory/dnc_read_content_weighting.py
python3 dnc/memory/dnc_read_vectors.py
python3 dnc/memory/dnc_read_weighting.py
python3 dnc/memory/dnc_sort_vector.py
python3 dnc/memory/dnc_temporal_link_matrix.py
python3 dnc/memory/dnc_usage_vector.py
python3 dnc/memory/dnc_vector_content_based_addressing.py
python3 dnc/memory/dnc_write_content_weighting.py
python3 dnc/memory/dnc_write_weighting.py
python3 dnc/top/dnc_interface_matrix.py
python3 dnc/top/dnc_interface_top.py
python3 dnc/top/dnc_interface_vector.py
python3 dnc/top/dnc_output_vector.py
python3 dnc/top/dnc_top.py
python3 dnc/trained/dnc_trained_top.py
python3 math/algebra/matrix/ntm_matrix_convolution.py
python3 math/algebra/matrix/ntm_matrix_inverse.py
python3 math/algebra/matrix/ntm_matrix_multiplication.py
python3 math/algebra/matrix/ntm_matrix_product.py
python3 math/algebra/matrix/ntm_matrix_summation.py
python3 math/algebra/matrix/ntm_matrix_transpose.py
python3 math/algebra/matrix/ntm_matrix_vector_convolution.py
python3 math/algebra/matrix/ntm_matrix_vector_product.py
python3 math/algebra/matrix/ntm_transpose_vector_product.py
python3 math/algebra/scalar/ntm_scalar_multiplication.py
python3 math/algebra/scalar/ntm_scalar_summation.py
python3 math/algebra/tensor/ntm_tensor_convolution.py
python3 math/algebra/tensor/ntm_tensor_inverse.py
python3 math/algebra/tensor/ntm_tensor_matrix_convolution.py
python3 math/algebra/tensor/ntm_tensor_matrix_product.py
python3 math/algebra/tensor/ntm_tensor_multiplication.py
python3 math/algebra/tensor/ntm_tensor_product.py
python3 math/algebra/tensor/ntm_tensor_summation.py
python3 math/algebra/tensor/ntm_tensor_transpose.py
python3 math/algebra/vector/ntm_dot_product.py
python3 math/algebra/vector/ntm_vector_convolution.py
python3 math/algebra/vector/ntm_vector_cosine_similarity.py
python3 math/algebra/vector/ntm_vector_module.py
python3 math/algebra/vector/ntm_vector_multiplication.py
python3 math/algebra/vector/ntm_vector_summation.py
python3 math/calculus/matrix/ntm_matrix_differentiation.py
python3 math/calculus/matrix/ntm_matrix_integration.py
python3 math/calculus/matrix/ntm_matrix_softmax.py
python3 math/calculus/tensor/ntm_tensor_differentiation.py
python3 math/calculus/tensor/ntm_tensor_integration.py
python3 math/calculus/tensor/ntm_tensor_softmax.py
python3 math/calculus/vector/ntm_vector_differentiation.py
python3 math/calculus/vector/ntm_vector_integration.py
python3 math/calculus/vector/ntm_vector_softmax.py
python3 math/function/matrix/ntm_matrix_logistic_function.py
python3 math/function/matrix/ntm_matrix_oneplus_function.py
python3 math/function/scalar/ntm_scalar_logistic_function.py
python3 math/function/scalar/ntm_scalar_oneplus_function.py
python3 math/function/vector/ntm_vector_logistic_function.py
python3 math/function/vector/ntm_vector_oneplus_function.py
python3 math/statitics/matrix/ntm_matrix_deviation.py
python3 math/statitics/matrix/ntm_matrix_mean.py
python3 math/statitics/scalar/ntm_scalar_deviation.py
python3 math/statitics/scalar/ntm_scalar_mean.py
python3 math/statitics/vector/ntm_vector_deviation.py
python3 math/statitics/vector/ntm_vector_mean.py
python3 ntm/memory/ntm_addressing.py
python3 ntm/memory/ntm_matrix_content_based_addressing.py
python3 ntm/memory/ntm_vector_content_based_addressing.py
python3 ntm/read_heads/ntm_reading.py
python3 ntm/top/ntm_interface_matrix.py
python3 ntm/top/ntm_interface_top.py
python3 ntm/top/ntm_interface_vector.py
python3 ntm/top/ntm_output_vector.py
python3 ntm/top/ntm_top.py
python3 ntm/trained/ntm_trained_top.py
python3 ntm/write_heads/ntm_erasing.py
python3 ntm/write_heads/ntm_writing.py
#python3 state/feedback/ntm_state_matrix_feedforward.py
#python3 state/feedback/ntm_state_matrix_input.py
#python3 state/feedback/ntm_state_matrix_output.py
#python3 state/feedback/ntm_state_matrix_state.py
#python3 state/outputs/ntm_state_vector_output.py
#python3 state/outputs/ntm_state_vector_state.py
#python3 state/top/ntm_state_top.py
python3 trainer/differentiation/ntm_matrix_controller_differentiation.py
python3 trainer/differentiation/ntm_vector_controller_differentiation.py
python3 trainer/FNN/ntm_fnn_b_trainer.py
python3 trainer/FNN/ntm_fnn_d_trainer.py
python3 trainer/FNN/ntm_fnn_k_trainer.py
python3 trainer/FNN/ntm_fnn_trainer.py
python3 trainer/FNN/ntm_fnn_u_trainer.py
python3 trainer/FNN/ntm_fnn_v_trainer.py
python3 trainer/FNN/ntm_fnn_w_trainer.py
python3 trainer/LSTM/activation/ntm_lstm_activation_b_trainer.py
python3 trainer/LSTM/activation/ntm_lstm_activation_d_trainer.py
python3 trainer/LSTM/activation/ntm_lstm_activation_k_trainer.py
python3 trainer/LSTM/activation/ntm_lstm_activation_trainer.py
python3 trainer/LSTM/activation/ntm_lstm_activation_u_trainer.py
python3 trainer/LSTM/activation/ntm_lstm_activation_v_trainer.py
python3 trainer/LSTM/activation/ntm_lstm_activation_w_trainer.py
python3 trainer/LSTM/forget/ntm_lstm_forget_b_trainer.py
python3 trainer/LSTM/forget/ntm_lstm_forget_d_trainer.py
python3 trainer/LSTM/forget/ntm_lstm_forget_k_trainer.py
python3 trainer/LSTM/forget/ntm_lstm_forget_trainer.py
python3 trainer/LSTM/forget/ntm_lstm_forget_u_trainer.py
python3 trainer/LSTM/forget/ntm_lstm_forget_v_trainer.py
python3 trainer/LSTM/forget/ntm_lstm_forget_w_trainer.py
python3 trainer/LSTM/input/ntm_lstm_input_b_trainer.py
python3 trainer/LSTM/input/ntm_lstm_input_d_trainer.py
python3 trainer/LSTM/input/ntm_lstm_input_k_trainer.py
python3 trainer/LSTM/input/ntm_lstm_input_trainer.py
python3 trainer/LSTM/input/ntm_lstm_input_u_trainer.py
python3 trainer/LSTM/input/ntm_lstm_input_v_trainer.py
python3 trainer/LSTM/input/ntm_lstm_input_w_trainer.py
python3 trainer/LSTM/output/ntm_lstm_output_b_trainer.py
python3 trainer/LSTM/output/ntm_lstm_output_d_trainer.py
python3 trainer/LSTM/output/ntm_lstm_output_k_trainer.py
python3 trainer/LSTM/output/ntm_lstm_output_trainer.py
python3 trainer/LSTM/output/ntm_lstm_output_u_trainer.py
python3 trainer/LSTM/output/ntm_lstm_output_v_trainer.py
python3 trainer/LSTM/output/ntm_lstm_output_w_trainer.py
