octave controller/FNN/convolutional/ntm_controller.tb.m
octave controller/FNN/standard/ntm_controller.tb.m
octave controller/LSTM/convolutional/ntm_activation_gate_vector.tb.m
octave controller/LSTM/convolutional/ntm_controller.tb.m
octave controller/LSTM/convolutional/ntm_forget_gate_vector.tb.m
octave controller/LSTM/convolutional/ntm_hidden_gate_vector.tb.m
octave controller/LSTM/convolutional/ntm_input_gate_vector.tb.m
octave controller/LSTM/convolutional/ntm_output_gate_vector.tb.m
octave controller/LSTM/convolutional/ntm_state_gate_vector.tb.m
octave controller/LSTM/standard/ntm_activation_gate_vector.tb.m
octave controller/LSTM/standard/ntm_controller.tb.m
octave controller/LSTM/standard/ntm_forget_gate_vector.tb.m
octave controller/LSTM/standard/ntm_hidden_gate_vector.tb.m
octave controller/LSTM/standard/ntm_input_gate_vector.tb.m
octave controller/LSTM/standard/ntm_output_gate_vector.tb.m
octave controller/LSTM/standard/ntm_state_gate_vector.tb.m
octave controller/transformer/components/ntm_masked_multi_head_attention.tb.m
octave controller/transformer/components/ntm_masked_scaled_dot_product_attention.tb.m
octave controller/transformer/components/ntm_multi_head_attention.tb.m
octave controller/transformer/components/ntm_scaled_dot_product_attention.tb.m
octave controller/transformer/fnn/ntm_fnn.tb.m
octave controller/transformer/functions/ntm_layer_norm.tb.m
octave controller/transformer/functions/ntm_positional_encoding.tb.m
octave controller/transformer/inputs/ntm_inputs_vector.tb.m
octave controller/transformer/inputs/ntm_keys_vector.tb.m
octave controller/transformer/inputs/ntm_queries_vector.tb.m
octave controller/transformer/inputs/ntm_values_vector.tb.m
octave controller/transformer/lstm/ntm_activation_gate_vector.tb.m
octave controller/transformer/lstm/ntm_forget_gate_vector.tb.m
octave controller/transformer/lstm/ntm_hidden_gate_vector.tb.m
octave controller/transformer/lstm/ntm_input_gate_vector.tb.m
octave controller/transformer/lstm/ntm_lstm.tb.m
octave controller/transformer/lstm/ntm_output_gate_vector.tb.m
octave controller/transformer/lstm/ntm_state_gate_vector.tb.m
octave controller/transformer/top/ntm_controller.tb.m
octave controller/transformer/top/ntm_decoder.tb.m
octave controller/transformer/top/ntm_encoder.tb.m
octave dnc/memory/dnc_addressing.tb.m
octave dnc/memory/dnc_allocation_weighting.tb.m
octave dnc/memory/dnc_backward_weighting.tb.m
octave dnc/memory/dnc_forward_weighting.tb.m
octave dnc/memory/dnc_matrix_content_based_addressing.tb.m
octave dnc/memory/dnc_memory_matrix.tb.m
octave dnc/memory/dnc_memory_retention_vector.tb.m
octave dnc/memory/dnc_precedence_weighting.tb.m
octave dnc/memory/dnc_read_content_weighting.tb.m
octave dnc/memory/dnc_read_vectors.tb.m
octave dnc/memory/dnc_read_weighting.tb.m
octave dnc/memory/dnc_sort_vector.tb.m
octave dnc/memory/dnc_temporal_link_matrix.tb.m
octave dnc/memory/dnc_usage_vector.tb.m
octave dnc/memory/dnc_vector_content_based_addressing.tb.m
octave dnc/memory/dnc_write_content_weighting.tb.m
octave dnc/memory/dnc_write_weighting.tb.m
octave dnc/top/dnc_interface_matrix.tb.m
octave dnc/top/dnc_interface_top.tb.m
octave dnc/top/dnc_interface_vector.tb.m
octave dnc/top/dnc_output_vector.tb.m
octave dnc/top/dnc_top.tb.m
octave dnc/trained/dnc_trained_top.tb.m
octave math/algebra/matrix/ntm_matrix_convolution.tb.m
octave math/algebra/matrix/ntm_matrix_inverse.tb.m
octave math/algebra/matrix/ntm_matrix_multiplication.tb.m
octave math/algebra/matrix/ntm_matrix_product.tb.m
octave math/algebra/matrix/ntm_matrix_summation.tb.m
octave math/algebra/matrix/ntm_matrix_transpose.tb.m
octave math/algebra/matrix/ntm_matrix_vector_convolution.tb.m
octave math/algebra/matrix/ntm_matrix_vector_product.tb.m
octave math/algebra/matrix/ntm_transpose_vector_product.tb.m
octave math/algebra/scalar/ntm_scalar_multiplication.tb.m
octave math/algebra/scalar/ntm_scalar_summation.tb.m
octave math/algebra/tensor/ntm_tensor_convolution.tb.m
octave math/algebra/tensor/ntm_tensor_inverse.tb.m
octave math/algebra/tensor/ntm_tensor_matrix_convolution.tb.m
octave math/algebra/tensor/ntm_tensor_matrix_product.tb.m
octave math/algebra/tensor/ntm_tensor_multiplication.tb.m
octave math/algebra/tensor/ntm_tensor_product.tb.m
octave math/algebra/tensor/ntm_tensor_summation.tb.m
octave math/algebra/tensor/ntm_tensor_transpose.tb.m
octave math/algebra/vector/ntm_dot_product.tb.m
octave math/algebra/vector/ntm_vector_convolution.tb.m
octave math/algebra/vector/ntm_vector_cosine_similarity.tb.m
octave math/algebra/vector/ntm_vector_module.tb.m
octave math/algebra/vector/ntm_vector_multiplication.tb.m
octave math/algebra/vector/ntm_vector_summation.tb.m
octave math/calculus/matrix/ntm_matrix_differentiation.tb.m
octave math/calculus/matrix/ntm_matrix_integration.tb.m
octave math/calculus/matrix/ntm_matrix_softmax.tb.m
octave math/calculus/tensor/ntm_tensor_differentiation.tb.m
octave math/calculus/tensor/ntm_tensor_integration.tb.m
octave math/calculus/tensor/ntm_tensor_softmax.tb.m
octave math/calculus/vector/ntm_vector_differentiation.tb.m
octave math/calculus/vector/ntm_vector_integration.tb.m
octave math/calculus/vector/ntm_vector_softmax.tb.m
octave math/function/matrix/ntm_matrix_logistic_function.tb.m
octave math/function/matrix/ntm_matrix_oneplus_function.tb.m
octave math/function/scalar/ntm_scalar_logistic_function.tb.m
octave math/function/scalar/ntm_scalar_oneplus_function.tb.m
octave math/function/vector/ntm_vector_logistic_function.tb.m
octave math/function/vector/ntm_vector_oneplus_function.tb.m
octave math/statitics/matrix/ntm_matrix_deviation.tb.m
octave math/statitics/matrix/ntm_matrix_mean.tb.m
octave math/statitics/scalar/ntm_scalar_deviation.tb.m
octave math/statitics/scalar/ntm_scalar_mean.tb.m
octave math/statitics/vector/ntm_vector_deviation.tb.m
octave math/statitics/vector/ntm_vector_mean.tb.m
octave ntm/memory/ntm_addressing.tb.m
octave ntm/memory/ntm_matrix_content_based_addressing.tb.m
octave ntm/memory/ntm_vector_content_based_addressing.tb.m
octave ntm/read_heads/ntm_reading.tb.m
octave ntm/top/ntm_interface_matrix.tb.m
octave ntm/top/ntm_interface_top.tb.m
octave ntm/top/ntm_interface_vector.tb.m
octave ntm/top/ntm_output_vector.tb.m
octave ntm/top/ntm_top.tb.m
octave ntm/trained/ntm_trained_top.tb.m
octave ntm/write_heads/ntm_erasing.tb.m
octave ntm/write_heads/ntm_writing.tb.m
octave state/feedback/ntm_state_matrix_feedforward.tb.m
octave state/feedback/ntm_state_matrix_input.tb.m
octave state/feedback/ntm_state_matrix_output.tb.m
octave state/feedback/ntm_state_matrix_state.tb.m
octave state/outputs/ntm_state_vector_output.tb.m
octave state/outputs/ntm_state_vector_state.tb.m
octave state/top/ntm_state_top.tb.m
octave trainer/differentiation/ntm_matrix_controller_differentiation.tb.m
octave trainer/differentiation/ntm_vector_controller_differentiation.tb.m
octave trainer/FNN/ntm_fnn_b_trainer.tb.m
octave trainer/FNN/ntm_fnn_d_trainer.tb.m
octave trainer/FNN/ntm_fnn_k_trainer.tb.m
octave trainer/FNN/ntm_fnn_trainer.tb.m
octave trainer/FNN/ntm_fnn_u_trainer.tb.m
octave trainer/FNN/ntm_fnn_v_trainer.tb.m
octave trainer/FNN/ntm_fnn_w_trainer.tb.m
octave trainer/LSTM/activation/ntm_lstm_activation_b_trainer.tb.m
octave trainer/LSTM/activation/ntm_lstm_activation_d_trainer.tb.m
octave trainer/LSTM/activation/ntm_lstm_activation_k_trainer.tb.m
octave trainer/LSTM/activation/ntm_lstm_activation_trainer.tb.m
octave trainer/LSTM/activation/ntm_lstm_activation_u_trainer.tb.m
octave trainer/LSTM/activation/ntm_lstm_activation_v_trainer.tb.m
octave trainer/LSTM/activation/ntm_lstm_activation_w_trainer.tb.m
octave trainer/LSTM/forget/ntm_lstm_forget_b_trainer.tb.m
octave trainer/LSTM/forget/ntm_lstm_forget_d_trainer.tb.m
octave trainer/LSTM/forget/ntm_lstm_forget_k_trainer.tb.m
octave trainer/LSTM/forget/ntm_lstm_forget_trainer.tb.m
octave trainer/LSTM/forget/ntm_lstm_forget_u_trainer.tb.m
octave trainer/LSTM/forget/ntm_lstm_forget_v_trainer.tb.m
octave trainer/LSTM/forget/ntm_lstm_forget_w_trainer.tb.m
octave trainer/LSTM/input/ntm_lstm_input_b_trainer.tb.m
octave trainer/LSTM/input/ntm_lstm_input_d_trainer.tb.m
octave trainer/LSTM/input/ntm_lstm_input_k_trainer.tb.m
octave trainer/LSTM/input/ntm_lstm_input_trainer.tb.m
octave trainer/LSTM/input/ntm_lstm_input_u_trainer.tb.m
octave trainer/LSTM/input/ntm_lstm_input_v_trainer.tb.m
octave trainer/LSTM/input/ntm_lstm_input_w_trainer.tb.m
octave trainer/LSTM/output/ntm_lstm_output_b_trainer.tb.m
octave trainer/LSTM/output/ntm_lstm_output_d_trainer.tb.m
octave trainer/LSTM/output/ntm_lstm_output_k_trainer.tb.m
octave trainer/LSTM/output/ntm_lstm_output_trainer.tb.m
octave trainer/LSTM/output/ntm_lstm_output_u_trainer.tb.m
octave trainer/LSTM/output/ntm_lstm_output_v_trainer.tb.m
octave trainer/LSTM/output/ntm_lstm_output_w_trainer.tb.m
