pandoc tex/scope/scope.md -s -o tex/scope/scope.pdf
pandoc tex/normative_references/normative_references.md -s -o tex/normative_references/normative_references.pdf
pandoc tex/terms_and_definitions/terms_and_definitions.md -s -o tex/terms_and_definitions/terms_and_definitions.pdf
pandoc tex/context_of_the_organization/context_of_the_organization.md -s -o tex/context_of_the_organization/context_of_the_organization.pdf
pandoc tex/leadership/leadership.md -s -o tex/leadership/leadership.pdf
pandoc tex/planning/planning.md -s -o tex/planning/planning.pdf
pandoc tex/support/support.md -s -o tex/support/support.pdf
pandoc tex/operation/operation.md -s -o tex/operation/operation.pdf
pandoc tex/performance_evaluation/performance_evaluation.md -s -o tex/performance_evaluation/performance_evaluation.pdf
pandoc tex/improvement/improvement.md -s -o tex/improvement/improvement.pdf
