touch library/bfm/ahb4/peripheral_design.scala
touch library/bfm/apb4/peripheral_design.scala
touch library/bfm/axi4/peripheral_design.scala
touch library/bfm/bb/peripheral_design.scala
touch library/bfm/peripheral_ahb4_test.scala
touch library/bfm/peripheral_apb4_test.scala
touch library/bfm/peripheral_axi4_test.scala
touch library/bfm/peripheral_bb_test.scala
touch library/bfm/peripheral_tl_test.scala
touch library/bfm/peripheral_wb_test.scala
touch library/bfm/tl/peripheral_design.scala
touch library/bfm/wb/peripheral_design.scala
touch library/core/ahb4/peripheral_design.scala
touch library/core/apb4/peripheral_design.scala
touch library/core/axi4/peripheral_design.scala
touch library/core/bb/peripheral_design.scala
touch library/core/peripheral_ahb4_test.scala
touch library/core/peripheral_apb4_test.scala
touch library/core/peripheral_axi4_test.scala
touch library/core/peripheral_bb_test.scala
touch library/core/peripheral_tl_test.scala
touch library/core/peripheral_wb_test.scala
touch library/core/tl/peripheral_design.scala
touch library/core/wb/peripheral_design.scala
