touch library/bfm/ahb4/peripheral_design.scala
touch library/bfm/apb4/peripheral_design.scala
touch library/bfm/axi4/peripheral_design.scala
touch library/bfm/bb/peripheral_design.scala
touch library/bfm/peripheral_ahb4_test.scala
touch library/bfm/peripheral_apb4_test.scala
touch library/bfm/peripheral_axi4_test.scala
touch library/bfm/peripheral_bb_test.scala
touch library/bfm/peripheral_tl_test.scala
touch library/bfm/peripheral_wb_test.scala
touch library/bfm/tl/peripheral_design.scala
touch library/bfm/wb/peripheral_design.scala
touch library/core/ahb4/peripheral_design.scala
touch library/core/apb4/peripheral_design.scala
touch library/core/axi4/peripheral_design.scala
touch library/core/bb/peripheral_design.scala
touch library/core/peripheral_ahb4_test.scala
touch library/core/peripheral_apb4_test.scala
touch library/core/peripheral_axi4_test.scala
touch library/core/peripheral_bb_test.scala
touch library/core/peripheral_tl_test.scala
touch library/core/peripheral_wb_test.scala
touch library/core/tl/peripheral_design.scala
touch library/core/wb/peripheral_design.scala
touch library/mpsoc/ahb4/peripheral_design.scala
touch library/mpsoc/apb4/peripheral_design.scala
touch library/mpsoc/axi4/peripheral_design.scala
touch library/mpsoc/bb/peripheral_design.scala
touch library/mpsoc/peripheral_ahb4_test.scala
touch library/mpsoc/peripheral_apb4_test.scala
touch library/mpsoc/peripheral_axi4_test.scala
touch library/mpsoc/peripheral_bb_test.scala
touch library/mpsoc/peripheral_tl_test.scala
touch library/mpsoc/peripheral_wb_test.scala
touch library/mpsoc/tl/peripheral_design.scala
touch library/mpsoc/wb/peripheral_design.scala
touch library/pu/ahb4/peripheral_design.scala
touch library/pu/apb4/peripheral_design.scala
touch library/pu/axi4/peripheral_design.scala
touch library/pu/bb/peripheral_design.scala
touch library/pu/peripheral_ahb4_test.scala
touch library/pu/peripheral_apb4_test.scala
touch library/pu/peripheral_axi4_test.scala
touch library/pu/peripheral_bb_test.scala
touch library/pu/peripheral_tl_test.scala
touch library/pu/peripheral_wb_test.scala
touch library/pu/tl/peripheral_design.scala
touch library/pu/wb/peripheral_design.scala
touch library/soc/ahb4/peripheral_design.scala
touch library/soc/apb4/peripheral_design.scala
touch library/soc/axi4/peripheral_design.scala
touch library/soc/bb/peripheral_design.scala
touch library/soc/peripheral_ahb4_test.scala
touch library/soc/peripheral_apb4_test.scala
touch library/soc/peripheral_axi4_test.scala
touch library/soc/peripheral_bb_test.scala
touch library/soc/peripheral_tl_test.scala
touch library/soc/peripheral_wb_test.scala
touch library/soc/tl/peripheral_design.scala
touch library/soc/wb/peripheral_design.scala
